# Generated by Django 3.1.4 on 2021-03-23 08:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App_Facturacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='user_creation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='venta_user_creation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='venta',
            name='user_updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='venta_user_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='seccion',
            name='user_creation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seccion_user_creation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='seccion',
            name='user_updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seccion_user_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='user_creation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proveedor_user_creation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='user_updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proveedor_user_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='producto',
            name='bloque',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_Facturacion.bloque'),
        ),
        migrations.AddField(
            model_name='producto',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_Facturacion.marca'),
        ),
        migrations.AddField(
            model_name='producto',
            name='posicion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_Facturacion.posicion'),
        ),
        migrations.AddField(
            model_name='producto',
            name='seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_Facturacion.seccion'),
        ),
        migrations.AddField(
            model_name='producto',
            name='user_creation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='producto_user_creation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='producto',
            name='user_updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='producto_user_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='posicion',
            name='user_creation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posicion_user_creation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='posicion',
            name='user_updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posicion_user_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pedido',
            name='user_creation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedido_user_creation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pedido',
            name='user_updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedido_user_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pedido',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='App_Facturacion.venta'),
        ),
        migrations.AddField(
            model_name='marca',
            name='user_creation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marca_user_creation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='marca',
            name='user_updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marca_user_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventario',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_Facturacion.producto'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='user_creation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventario_user_creation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventario',
            name='user_updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventario_user_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='galeria',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_Facturacion.producto'),
        ),
        migrations.AddField(
            model_name='galeria',
            name='user_creation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='galeria_user_creation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='galeria',
            name='user_updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='galeria_user_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='empresa',
            name='user_creation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empresa_user_creation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='empresa',
            name='user_updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empresa_user_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='devolucion_detalle_compra',
            name='devolucion_compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_Facturacion.devolucion_compra'),
        ),
        migrations.AddField(
            model_name='devolucion_detalle_compra',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_Facturacion.producto'),
        ),
        migrations.AddField(
            model_name='devolucion_detalle_compra',
            name='user_creation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devolucion_detalle_compra_user_creation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='devolucion_detalle_compra',
            name='user_updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devolucion_detalle_compra_user_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='devolucion_compra',
            name='compra',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='App_Facturacion.compra'),
        ),
        migrations.AddField(
            model_name='devolucion_compra',
            name='user_creation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devolucion_compra_user_creation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='devolucion_compra',
            name='user_updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devolucion_compra_user_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detalle_venta',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='App_Facturacion.producto'),
        ),
        migrations.AddField(
            model_name='detalle_venta',
            name='user_creation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalle_user_creation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detalle_venta',
            name='user_updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalle_user_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detalle_venta',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_Facturacion.venta'),
        ),
        migrations.AddField(
            model_name='detalle_compra',
            name='compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_Facturacion.compra'),
        ),
        migrations.AddField(
            model_name='detalle_compra',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_Facturacion.producto'),
        ),
        migrations.AddField(
            model_name='detalle_compra',
            name='user_creation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalle_compra_user_creation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detalle_compra',
            name='user_updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalle_compra_user_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cuentas_compra',
            name='compra',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='App_Facturacion.compra'),
        ),
        migrations.AddField(
            model_name='cuentas_compra',
            name='user_creation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuentas_compra_user_creation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cuentas_compra',
            name='user_updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuentas_compra_user_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cuentas',
            name='user_creation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuentas_user_creation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cuentas',
            name='user_updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuentas_user_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cuentas',
            name='venta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='App_Facturacion.venta'),
        ),
        migrations.AddField(
            model_name='compra',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_Facturacion.proveedor'),
        ),
        migrations.AddField(
            model_name='compra',
            name='user_creation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compra_user_creation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compra',
            name='user_updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compra_user_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cliente',
            name='user_creation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cliente_user_creation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cliente',
            name='user_updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cliente_user_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bloque',
            name='user_creation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bloque_user_creation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bloque',
            name='user_updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bloque_user_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='abono_compra',
            name='cuentas_compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_Facturacion.cuentas_compra'),
        ),
        migrations.AddField(
            model_name='abono_compra',
            name='user_creation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='abono_compra_user_creation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='abono_compra',
            name='user_updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='abono_compra_user_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='abono',
            name='cuentas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_Facturacion.cuentas'),
        ),
        migrations.AddField(
            model_name='abono',
            name='user_creation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='abono_user_creation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='abono',
            name='user_updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='abono_user_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
