# Generated by Django 3.1.4 on 2021-03-23 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_Facturacion', '0002_auto_20210323_0856'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='fecha_fin',
            new_name='fecha',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='fecha_inicio',
            new_name='fecha_entrega',
        ),
        migrations.AddField(
            model_name='abono',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='estado_entrega',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pedido',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='pedido',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='ubicacion_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='estado_pedido',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='venta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='App_Facturacion.venta'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=0.12, max_digits=5),
        ),
    ]
