# Generated by Django 3.1.4 on 2021-04-10 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Facturacion', '0007_auto_20210410_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='iva_base',
            field=models.DecimalField(decimal_places=2, default=0.12, max_digits=3),
        ),
    ]
