# Generated by Django 3.1.4 on 2021-04-10 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Facturacion', '0008_venta_iva_base'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentas',
            name='estado_venta',
            field=models.BooleanField(default=True),
        ),
    ]
