# Generated by Django 3.1.4 on 2021-04-10 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Facturacion', '0009_auto_20210410_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle_venta',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
