# Generated by Django 3.1.4 on 2021-04-12 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Facturacion', '0010_detalle_venta_descuento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='descripcion',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
