# Generated by Django 3.1.4 on 2021-04-12 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Facturacion', '0011_auto_20210412_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='descripcion',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
    ]
