# Generated by Django 3.1.4 on 2021-04-22 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Facturacion', '0014_auto_20210417_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_compra',
            name='precio',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=6),
        ),
    ]
