# Generated by Django 3.1.4 on 2021-04-22 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Facturacion', '0015_auto_20210422_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devolucion_detalle_compra',
            name='precio',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=9),
        ),
    ]
