# Generated by Django 3.1.4 on 2021-04-22 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Facturacion', '0016_auto_20210422_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio_bruto',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=7, verbose_name='Precio Base'),
        ),
    ]
