# Generated by Django 3.1.4 on 2021-05-03 21:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App_Facturacion', '0018_devolucion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devolucion_Detalle_Venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('descuento', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('devolucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_Facturacion.devolucion')),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='App_Facturacion.inventario')),
                ('user_creation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devolucion_detalle_user_creation', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devolucion_detalle_user_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
                'db_table': 'devolucion_detalle',
                'ordering': ['id'],
            },
        ),
    ]
