# Generated by Django 3.1.4 on 2021-05-04 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Facturacion', '0019_devolucion_detalle_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='estado_devolucion',
            field=models.BooleanField(default=False),
        ),
    ]
