# Generated by Django 3.1.4 on 2021-05-06 22:06

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App_Facturacion', '0020_venta_estado_devolucion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto_Deteriorado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(max_length=100)),
                ('fecha', models.DateField(default=datetime.datetime.now)),
                ('precio', models.DecimalField(decimal_places=3, default=0.0, max_digits=9)),
                ('cantidad', models.IntegerField()),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('tipo_problema', models.BooleanField(default=True)),
                ('estado', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_Facturacion.inventario')),
                ('user_creation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='producto_deteriorado_user_creation', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='producto_deteriorado_user_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Producto Deteriorado',
                'verbose_name_plural': 'Productos Deteriorados',
                'db_table': 'producto_deteriorado',
                'ordering': ['id'],
            },
        ),
    ]
