# Generated by Django 3.1.4 on 2021-05-07 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Facturacion', '0021_producto_deteriorado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto_deteriorado',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
    ]
