# Generated by Django 3.1.4 on 2021-05-08 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Facturacion', '0022_auto_20210507_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto_deteriorado',
            name='tipo_gestion',
            field=models.BooleanField(default=True),
        ),
    ]
