# Generated by Django 3.1.4 on 2021-05-08 13:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App_Facturacion', '0023_producto_deteriorado_tipo_gestion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Producto_Deteriorado',
            new_name='Gestion_Inventario',
        ),
    ]
