# Generated by Django 3.1.4 on 2021-05-08 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App_Facturacion', '0024_auto_20210508_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gestion_inventario',
            name='user_creation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gestion_invnetario_user_creation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gestion_inventario',
            name='user_updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gestion_inventario_user_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
