# Generated by Django 3.1.4 on 2021-05-08 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Facturacion', '0025_auto_20210508_1304'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gestion_inventario',
            options={'ordering': ['id'], 'verbose_name': 'Gestion Inventario', 'verbose_name_plural': 'Gestion Inventario'},
        ),
        migrations.AlterModelTable(
            name='gestion_inventario',
            table='gestion_inventario',
        ),
    ]
