# Generated by Django 3.1.4 on 2021-05-08 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Facturacion', '0027_auto_20210508_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gestion_inventario',
            name='descripcion',
            field=models.TextField(max_length=200),
        ),
    ]
